FLAGS=`pkg-config --libs opencv4`

all:
	#g++ stereo_calib.cpp -o main -I /usr/local/include/opencv4 -L /usr/local/lib $(FLAGS)
	g++ cam.cpp -o main -I /usr/local/include/opencv4 -L /usr/local/lib $(FLAGS)
	#g++ fps.cpp -o main -I /usr/local/include/opencv4 -L /usr/local/lib $(FLAGS)
